component_depth: 1
languages:
- java
- script
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/quilt/.*
- ./bin/org/quilt/bytecode/.*
- ./bin/org/quilt/cl/.*
- ./bin/org/quilt/cover/.*
- ./bin/org/quilt/cover/seg/.*
- ./bin/org/quilt/cover/stmt/.*
- ./bin/org/quilt/exception/.*
- ./bin/org/quilt/framework/.*
- ./bin/org/quilt/frontend/.*
- ./bin/org/quilt/frontend/ant/.*
- ./bin/org/quilt/graph/.*
- ./bin/org/quilt/reg/.*
- ./bin/org/quilt/reports/.*
- ./bin/org/quilt/runner/.*
- ./bin/org/quilt/textui/.*
- ./lib/.*
- ./xdocs/.*
- ./xdocs/community/.*
- ./xdocs/developers/.*
- ./xdocs/images/.*
- ./xdocs/quilt-0.4/.*
- ./xdocs/quilt-0.4/apidocs/.*
- ./xdocs/quilt-0.4/apidocs/junit/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/adapter/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/adapter/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ant/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ant/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/ball94/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/ball94/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/generic/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/generic/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/none/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/none/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/state/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/cover/state/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/exception/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/exception/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/framework/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/framework/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/reports/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/reports/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/runner/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/runner/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/textui/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/textui/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ui/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ui/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ui/jips/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/ui/jips/class-use/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/util/.*
- ./xdocs/quilt-0.4/apidocs/junit/quilt/util/class-use/.*
- ./xdocs/quilt-0.4/cgi/.*
- ./xdocs/quilt-0.4/images/.*
- ./xdocs/quilt-0.4/style/.*
- ./xdocs/quilt-0.4/xref/.*
- ./xdocs/quilt-0.4/xref/junit/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/adapter/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/ant/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/cover/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/cover/ball94/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/cover/generic/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/cover/none/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/cover/state/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/exception/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/framework/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/reports/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/runner/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/textui/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/ui/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/ui/jips/.*
- ./xdocs/quilt-0.4/xref/junit/quilt/util/.*
- ./xdocs/tutorials/.*
